import 'package:flutter/material.dart';
import '../models/country.dart';
import '../models/service_category.dart';
import '../models/calculator_item.dart';

class DataProvider extends ChangeNotifier {
  List<Country> _countries = [];
  List<ServiceCategory> _categories = [];
  final List<CalculatorItem> _calculatorItems = [];
  String? _selectedCountryCode;
  bool _isLoading = false;

  List<Country> get countries => _countries;
  List<ServiceCategory> get categories => _categories;
  List<CalculatorItem> get calculatorItems => _calculatorItems;
  String? get selectedCountryCode => _selectedCountryCode;
  bool get isLoading => _isLoading;

  Country? get selectedCountry {
    if (_selectedCountryCode == null) return null;
    try {
      return _countries.firstWhere((c) => c.code == _selectedCountryCode);
    } catch (e) {
      return null;
    }
  }

  double get calculatorTotal {
    return _calculatorItems.fold(0.0, (sum, item) => sum + item.total);
  }

  void selectCountry(String countryCode) {
    _selectedCountryCode = countryCode;
    notifyListeners();
  }

  void addCalculatorItem(CalculatorItem item) {
    _calculatorItems.add(item);
    notifyListeners();
  }

  void updateCalculatorItem(int index, CalculatorItem item) {
    if (index >= 0 && index < _calculatorItems.length) {
      _calculatorItems[index] = item;
      notifyListeners();
    }
  }

  void removeCalculatorItem(int index) {
    if (index >= 0 && index < _calculatorItems.length) {
      _calculatorItems.removeAt(index);
      notifyListeners();
    }
  }

  void clearCalculator() {
    _calculatorItems.clear();
    notifyListeners();
  }

  Future<void> loadData() async {
    _isLoading = true;
    notifyListeners();

    // Загрузка данных по странам
    _countries = _getEuropeanCountries();
    
    // Загрузка категорий услуг
    _categories = _getServiceCategories();
    
    // Установка страны по умолчанию
    if (_selectedCountryCode == null && _countries.isNotEmpty) {
      _selectedCountryCode = _countries.first.code;
    }

    _isLoading = false;
    notifyListeners();
  }

  List<Country> _getEuropeanCountries() {
    return [
      Country(
        id: 'de',
        name: 'Germany',
        nameRu: 'Германия',
        code: 'DE',
        flagEmoji: '🇩🇪',
        averagePricePerSqm: 1850.0,
      ),
      Country(
        id: 'fr',
        name: 'France',
        nameRu: 'Франция',
        code: 'FR',
        flagEmoji: '🇫🇷',
        averagePricePerSqm: 1750.0,
      ),
      Country(
        id: 'it',
        name: 'Italy',
        nameRu: 'Италия',
        code: 'IT',
        flagEmoji: '🇮🇹',
        averagePricePerSqm: 1650.0,
      ),
      Country(
        id: 'es',
        name: 'Spain',
        nameRu: 'Испания',
        code: 'ES',
        flagEmoji: '🇪🇸',
        averagePricePerSqm: 1450.0,
      ),
      Country(
        id: 'pl',
        name: 'Poland',
        nameRu: 'Польша',
        code: 'PL',
        flagEmoji: '🇵🇱',
        averagePricePerSqm: 1200.0,
      ),
      Country(
        id: 'nl',
        name: 'Netherlands',
        nameRu: 'Нидерланды',
        code: 'NL',
        flagEmoji: '🇳🇱',
        averagePricePerSqm: 2100.0,
      ),
      Country(
        id: 'be',
        name: 'Belgium',
        nameRu: 'Бельгия',
        code: 'BE',
        flagEmoji: '🇧🇪',
        averagePricePerSqm: 1900.0,
      ),
      Country(
        id: 'at',
        name: 'Austria',
        nameRu: 'Австрия',
        code: 'AT',
        flagEmoji: '🇦🇹',
        averagePricePerSqm: 1950.0,
      ),
      Country(
        id: 'ch',
        name: 'Switzerland',
        nameRu: 'Швейцария',
        code: 'CH',
        flagEmoji: '🇨🇭',
        averagePricePerSqm: 2800.0,
        currency: 'CHF',
      ),
      Country(
        id: 'cz',
        name: 'Czech Republic',
        nameRu: 'Чехия',
        code: 'CZ',
        flagEmoji: '🇨🇿',
        averagePricePerSqm: 1350.0,
      ),
      Country(
        id: 'pt',
        name: 'Portugal',
        nameRu: 'Португалия',
        code: 'PT',
        flagEmoji: '🇵🇹',
        averagePricePerSqm: 1250.0,
      ),
      Country(
        id: 'se',
        name: 'Sweden',
        nameRu: 'Швеция',
        code: 'SE',
        flagEmoji: '🇸🇪',
        averagePricePerSqm: 2200.0,
      ),
      Country(
        id: 'dk',
        name: 'Denmark',
        nameRu: 'Дания',
        code: 'DK',
        flagEmoji: '🇩🇰',
        averagePricePerSqm: 2300.0,
      ),
      Country(
        id: 'no',
        name: 'Norway',
        nameRu: 'Норвегия',
        code: 'NO',
        flagEmoji: '🇳🇴',
        averagePricePerSqm: 2500.0,
      ),
      Country(
        id: 'fi',
        name: 'Finland',
        nameRu: 'Финляндия',
        code: 'FI',
        flagEmoji: '🇫🇮',
        averagePricePerSqm: 2000.0,
      ),
    ];
  }

  List<ServiceCategory> _getServiceCategories() {
    return [
      ServiceCategory(
        id: 'painting',
        name: 'Painting Works',
        nameRu: 'Малярные работы',
        description: 'Interior and exterior painting',
        descriptionRu: 'Внутренние и наружные покрасочные работы',
        icon: Icons.format_paint,
        color: const Color(0xFFFFC107),
        services: _getPaintingServices(),
      ),
      ServiceCategory(
        id: 'electrical',
        name: 'Electrical Works',
        nameRu: 'Электромонтажные работы',
        description: 'Electrical installation and wiring',
        descriptionRu: 'Электромонтаж и проводка',
        icon: Icons.electric_bolt,
        color: const Color(0xFF2196F3),
        services: _getElectricalServices(),
      ),
      ServiceCategory(
        id: 'plumbing',
        name: 'Plumbing Works',
        nameRu: 'Сантехнические работы',
        description: 'Water supply and drainage',
        descriptionRu: 'Водоснабжение и канализация',
        icon: Icons.plumbing,
        color: const Color(0xFF4CAF50),
        services: _getPlumbingServices(),
      ),
      ServiceCategory(
        id: 'flooring',
        name: 'Flooring Works',
        nameRu: 'Напольные покрытия',
        description: 'Floor installation and finishing',
        descriptionRu: 'Укладка и отделка полов',
        icon: Icons.layers,
        color: const Color(0xFF9C27B0),
        services: _getFlooringServices(),
      ),
      ServiceCategory(
        id: 'tiling',
        name: 'Tiling Works',
        nameRu: 'Облицовочные работы',
        description: 'Wall and floor tiling',
        descriptionRu: 'Облицовка стен и полов плиткой',
        icon: Icons.grid_on,
        color: const Color(0xFFFF5722),
        services: _getTilingServices(),
      ),
      ServiceCategory(
        id: 'carpentry',
        name: 'Carpentry Works',
        nameRu: 'Столярные работы',
        description: 'Woodwork and furniture',
        descriptionRu: 'Деревянные конструкции и мебель',
        icon: Icons.carpenter,
        color: const Color(0xFF795548),
        services: _getCarpentryServices(),
      ),
      ServiceCategory(
        id: 'roofing',
        name: 'Roofing Works',
        nameRu: 'Кровельные работы',
        description: 'Roof installation and repair',
        descriptionRu: 'Монтаж и ремонт кровли',
        icon: Icons.roofing,
        color: const Color(0xFF607D8B),
        services: _getRoofingServices(),
      ),
      ServiceCategory(
        id: 'facade',
        name: 'Facade Works',
        nameRu: 'Фасадные работы',
        description: 'Exterior wall finishing',
        descriptionRu: 'Отделка наружных стен',
        icon: Icons.apartment,
        color: const Color(0xFF00BCD4),
        services: _getFacadeServices(),
      ),
      ServiceCategory(
        id: 'hvac',
        name: 'HVAC Works',
        nameRu: 'Отопление и вентиляция',
        description: 'Heating, ventilation, air conditioning',
        descriptionRu: 'Системы отопления, вентиляции и кондиционирования',
        icon: Icons.ac_unit,
        color: const Color(0xFF03A9F4),
        services: _getHVACServices(),
      ),
      ServiceCategory(
        id: 'glazing',
        name: 'Glazing Works',
        nameRu: 'Остекление',
        description: 'Window and door installation',
        descriptionRu: 'Установка окон и дверей',
        icon: Icons.window,
        color: const Color(0xFF00ACC1),
        services: _getGlazingServices(),
      ),
      ServiceCategory(
        id: 'plastering',
        name: 'Plastering & Drywall',
        nameRu: 'Штукатурка и гипсокартон',
        description: 'Wall plastering and drywall installation',
        descriptionRu: 'Штукатурные работы и монтаж гипсокартона',
        icon: Icons.handyman,
        color: const Color(0xFFCDDC39),
        services: _getPlasteringServices(),
      ),
      ServiceCategory(
        id: 'landscaping',
        name: 'Landscaping Works',
        nameRu: 'Ландшафтные работы',
        description: 'Garden and outdoor works',
        descriptionRu: 'Благоустройство и озеленение',
        icon: Icons.grass,
        color: const Color(0xFF8BC34A),
        services: _getLandscapingServices(),
      ),
    ];
  }

  List<ServiceItem> _getPaintingServices() {
    return [
      ServiceItem(
        id: 'painting_interior_walls',
        categoryId: 'painting',
        name: 'Interior Wall Painting',
        nameRu: 'Покраска внутренних стен',
        unit: 'sqm',
        unitRu: 'м²',
        materialsCostRatio: 1.3,
        pricesByCountry: {
          'DE': PriceRange(min: 15, max: 30, average: 22),
          'FR': PriceRange(min: 14, max: 28, average: 20),
          'IT': PriceRange(min: 12, max: 25, average: 18),
          'ES': PriceRange(min: 10, max: 22, average: 16),
          'PL': PriceRange(min: 8, max: 18, average: 13),
          'NL': PriceRange(min: 18, max: 35, average: 26),
          'BE': PriceRange(min: 16, max: 32, average: 24),
          'AT': PriceRange(min: 16, max: 32, average: 24),
          'CH': PriceRange(min: 25, max: 50, average: 37),
          'CZ': PriceRange(min: 9, max: 20, average: 14),
          'PT': PriceRange(min: 9, max: 20, average: 14),
          'SE': PriceRange(min: 20, max: 40, average: 30),
          'DK': PriceRange(min: 22, max: 42, average: 32),
          'NO': PriceRange(min: 24, max: 45, average: 34),
          'FI': PriceRange(min: 19, max: 38, average: 28),
        },
      ),
      ServiceItem(
        id: 'painting_ceiling',
        categoryId: 'painting',
        name: 'Ceiling Painting',
        nameRu: 'Покраска потолков',
        unit: 'sqm',
        unitRu: 'м²',
        materialsCostRatio: 1.35,
        pricesByCountry: {
          'DE': PriceRange(min: 18, max: 35, average: 26),
          'FR': PriceRange(min: 17, max: 33, average: 25),
          'IT': PriceRange(min: 15, max: 30, average: 22),
          'ES': PriceRange(min: 13, max: 26, average: 19),
          'PL': PriceRange(min: 10, max: 22, average: 16),
          'NL': PriceRange(min: 21, max: 40, average: 30),
          'BE': PriceRange(min: 19, max: 37, average: 28),
          'AT': PriceRange(min: 19, max: 37, average: 28),
          'CH': PriceRange(min: 30, max: 58, average: 44),
          'CZ': PriceRange(min: 11, max: 24, average: 17),
          'PT': PriceRange(min: 11, max: 24, average: 17),
          'SE': PriceRange(min: 24, max: 46, average: 35),
          'DK': PriceRange(min: 26, max: 48, average: 37),
          'NO': PriceRange(min: 28, max: 52, average: 40),
          'FI': PriceRange(min: 22, max: 44, average: 33),
        },
      ),
      ServiceItem(
        id: 'painting_exterior_facade',
        categoryId: 'painting',
        name: 'Exterior Facade Painting',
        nameRu: 'Покраска фасада',
        unit: 'sqm',
        unitRu: 'м²',
        materialsCostRatio: 1.4,
        pricesByCountry: {
          'DE': PriceRange(min: 20, max: 45, average: 32),
          'FR': PriceRange(min: 19, max: 42, average: 30),
          'IT': PriceRange(min: 17, max: 38, average: 27),
          'ES': PriceRange(min: 15, max: 33, average: 24),
          'PL': PriceRange(min: 11, max: 25, average: 18),
          'NL': PriceRange(min: 24, max: 52, average: 38),
          'BE': PriceRange(min: 22, max: 48, average: 35),
          'AT': PriceRange(min: 22, max: 48, average: 35),
          'CH': PriceRange(min: 35, max: 70, average: 52),
          'CZ': PriceRange(min: 13, max: 29, average: 21),
          'PT': PriceRange(min: 13, max: 29, average: 21),
          'SE': PriceRange(min: 27, max: 56, average: 41),
          'DK': PriceRange(min: 29, max: 58, average: 43),
          'NO': PriceRange(min: 31, max: 62, average: 46),
          'FI': PriceRange(min: 26, max: 54, average: 40),
        },
      ),
      ServiceItem(
        id: 'painting_wallpaper',
        categoryId: 'painting',
        name: 'Wallpaper Installation',
        nameRu: 'Поклейка обоев',
        unit: 'sqm',
        unitRu: 'м²',
        materialsCostRatio: 1.45,
        pricesByCountry: {
          'DE': PriceRange(min: 12, max: 25, average: 18),
          'FR': PriceRange(min: 11, max: 23, average: 17),
          'IT': PriceRange(min: 10, max: 21, average: 15),
          'ES': PriceRange(min: 8, max: 18, average: 13),
          'PL': PriceRange(min: 6, max: 14, average: 10),
          'NL': PriceRange(min: 14, max: 29, average: 21),
          'BE': PriceRange(min: 13, max: 27, average: 20),
          'AT': PriceRange(min: 13, max: 27, average: 20),
          'CH': PriceRange(min: 20, max: 40, average: 30),
          'CZ': PriceRange(min: 7, max: 16, average: 11),
          'PT': PriceRange(min: 7, max: 16, average: 11),
          'SE': PriceRange(min: 16, max: 32, average: 24),
          'DK': PriceRange(min: 17, max: 34, average: 25),
          'NO': PriceRange(min: 18, max: 36, average: 27),
          'FI': PriceRange(min: 15, max: 31, average: 23),
        },
      ),
      ServiceItem(
        id: 'painting_decorative',
        categoryId: 'painting',
        name: 'Decorative Painting',
        nameRu: 'Декоративная покраска',
        unit: 'sqm',
        unitRu: 'м²',
        materialsCostRatio: 1.5,
        pricesByCountry: {
          'DE': PriceRange(min: 30, max: 70, average: 50),
          'FR': PriceRange(min: 28, max: 65, average: 46),
          'IT': PriceRange(min: 25, max: 60, average: 42),
          'ES': PriceRange(min: 22, max: 52, average: 37),
          'PL': PriceRange(min: 16, max: 38, average: 27),
          'NL': PriceRange(min: 35, max: 80, average: 57),
          'BE': PriceRange(min: 32, max: 75, average: 53),
          'AT': PriceRange(min: 32, max: 75, average: 53),
          'CH': PriceRange(min: 50, max: 110, average: 80),
          'CZ': PriceRange(min: 18, max: 44, average: 31),
          'PT': PriceRange(min: 18, max: 44, average: 31),
          'SE': PriceRange(min: 38, max: 85, average: 61),
          'DK': PriceRange(min: 40, max: 90, average: 65),
          'NO': PriceRange(min: 43, max: 95, average: 69),
          'FI': PriceRange(min: 37, max: 83, average: 60),
        },
      ),
    ];
  }

  List<ServiceItem> _getElectricalServices() {
    return [
      ServiceItem(
        id: 'electrical_outlet',
        categoryId: 'electrical',
        name: 'Electrical Outlet Installation',
        nameRu: 'Установка розетки',
        unit: 'piece',
        unitRu: 'шт',
        materialsCostRatio: 1.7,
        pricesByCountry: {
          'DE': PriceRange(min: 50, max: 120, average: 85),
          'FR': PriceRange(min: 45, max: 110, average: 77),
          'IT': PriceRange(min: 40, max: 100, average: 70),
          'ES': PriceRange(min: 35, max: 85, average: 60),
          'PL': PriceRange(min: 25, max: 60, average: 42),
          'NL': PriceRange(min: 60, max: 140, average: 100),
          'BE': PriceRange(min: 55, max: 130, average: 92),
          'AT': PriceRange(min: 55, max: 130, average: 92),
          'CH': PriceRange(min: 80, max: 180, average: 130),
          'CZ': PriceRange(min: 30, max: 70, average: 50),
          'PT': PriceRange(min: 30, max: 70, average: 50),
          'SE': PriceRange(min: 65, max: 150, average: 107),
          'DK': PriceRange(min: 70, max: 160, average: 115),
          'NO': PriceRange(min: 75, max: 170, average: 122),
          'FI': PriceRange(min: 60, max: 145, average: 102),
        },
      ),
      ServiceItem(
        id: 'electrical_switch',
        categoryId: 'electrical',
        name: 'Light Switch Installation',
        nameRu: 'Установка выключателя',
        unit: 'piece',
        unitRu: 'шт',
        materialsCostRatio: 1.6,
        pricesByCountry: {
          'DE': PriceRange(min: 45, max: 110, average: 77),
          'FR': PriceRange(min: 40, max: 100, average: 70),
          'IT': PriceRange(min: 35, max: 90, average: 62),
          'ES': PriceRange(min: 30, max: 75, average: 52),
          'PL': PriceRange(min: 22, max: 55, average: 38),
          'NL': PriceRange(min: 55, max: 130, average: 92),
          'BE': PriceRange(min: 50, max: 120, average: 85),
          'AT': PriceRange(min: 50, max: 120, average: 85),
          'CH': PriceRange(min: 75, max: 165, average: 120),
          'CZ': PriceRange(min: 27, max: 65, average: 46),
          'PT': PriceRange(min: 27, max: 65, average: 46),
          'SE': PriceRange(min: 60, max: 140, average: 100),
          'DK': PriceRange(min: 65, max: 150, average: 107),
          'NO': PriceRange(min: 70, max: 160, average: 115),
          'FI': PriceRange(min: 55, max: 135, average: 95),
        },
      ),
      ServiceItem(
        id: 'electrical_double_outlet',
        categoryId: 'electrical',
        name: 'Double Outlet Installation',
        nameRu: 'Установка двойной розетки',
        unit: 'piece',
        unitRu: 'шт',
        materialsCostRatio: 1.9,
        pricesByCountry: {
          'DE': PriceRange(min: 45, max: 75, average: 58),
          'FR': PriceRange(min: 42, max: 71, average: 55),
          'IT': PriceRange(min: 38, max: 63, average: 49),
          'ES': PriceRange(min: 33, max: 56, average: 43),
          'PL': PriceRange(min: 24, max: 41, average: 31),
          'NL': PriceRange(min: 51, max: 86, average: 66),
          'BE': PriceRange(min: 47, max: 78, average: 60),
          'AT': PriceRange(min: 47, max: 78, average: 60),
          'CH': PriceRange(min: 74, max: 123, average: 95),
          'CZ': PriceRange(min: 27, max: 45, average: 34),
          'PT': PriceRange(min: 27, max: 45, average: 34),
          'SE': PriceRange(min: 58, max: 97, average: 75),
          'DK': PriceRange(min: 62, max: 105, average: 81),
          'NO': PriceRange(min: 67, max: 112, average: 87),
          'FI': PriceRange(min: 56, max: 93, average: 72),
        },
      ),
      ServiceItem(
        id: 'electrical_tv_outlet',
        categoryId: 'electrical',
        name: 'TV Outlet Installation',
        nameRu: 'Установка ТВ-розетки',
        unit: 'piece',
        unitRu: 'шт',
        materialsCostRatio: 1.9,
        pricesByCountry: {
          'DE': PriceRange(min: 40, max: 70, average: 52),
          'FR': PriceRange(min: 38, max: 66, average: 49),
          'IT': PriceRange(min: 34, max: 59, average: 44),
          'ES': PriceRange(min: 30, max: 52, average: 39),
          'PL': PriceRange(min: 22, max: 38, average: 28),
          'NL': PriceRange(min: 46, max: 80, average: 59),
          'BE': PriceRange(min: 42, max: 73, average: 54),
          'AT': PriceRange(min: 42, max: 73, average: 54),
          'CH': PriceRange(min: 66, max: 115, average: 85),
          'CZ': PriceRange(min: 24, max: 42, average: 31),
          'PT': PriceRange(min: 24, max: 42, average: 31),
          'SE': PriceRange(min: 52, max: 91, average: 67),
          'DK': PriceRange(min: 56, max: 98, average: 72),
          'NO': PriceRange(min: 60, max: 105, average: 78),
          'FI': PriceRange(min: 50, max: 87, average: 65),
        },
      ),
      ServiceItem(
        id: 'electrical_ceiling_light',
        categoryId: 'electrical',
        name: 'Ceiling Light Installation',
        nameRu: 'Установка потолочного светильника',
        unit: 'piece',
        unitRu: 'шт',
        materialsCostRatio: 2.0,
        pricesByCountry: {
          'DE': PriceRange(min: 50, max: 90, average: 65),
          'FR': PriceRange(min: 47, max: 85, average: 61),
          'IT': PriceRange(min: 42, max: 76, average: 55),
          'ES': PriceRange(min: 37, max: 67, average: 48),
          'PL': PriceRange(min: 27, max: 49, average: 35),
          'NL': PriceRange(min: 57, max: 103, average: 74),
          'BE': PriceRange(min: 52, max: 94, average: 68),
          'AT': PriceRange(min: 52, max: 94, average: 68),
          'CH': PriceRange(min: 82, max: 148, average: 107),
          'CZ': PriceRange(min: 30, max: 54, average: 39),
          'PT': PriceRange(min: 30, max: 54, average: 39),
          'SE': PriceRange(min: 65, max: 117, average: 84),
          'DK': PriceRange(min: 70, max: 125, average: 91),
          'NO': PriceRange(min: 75, max: 135, average: 97),
          'FI': PriceRange(min: 62, max: 112, average: 81),
        },
      ),
      ServiceItem(
        id: 'electrical_led_strip',
        categoryId: 'electrical',
        name: 'LED Strip Installation',
        nameRu: 'Монтаж LED-ленты',
        unit: 'meter',
        unitRu: 'пог.м',
        materialsCostRatio: 2.5,
        pricesByCountry: {
          'DE': PriceRange(min: 15, max: 30, average: 22),
          'FR': PriceRange(min: 14, max: 28, average: 20),
          'IT': PriceRange(min: 12, max: 25, average: 18),
          'ES': PriceRange(min: 11, max: 22, average: 16),
          'PL': PriceRange(min: 8, max: 16, average: 12),
          'NL': PriceRange(min: 17, max: 34, average: 25),
          'BE': PriceRange(min: 15, max: 31, average: 23),
          'AT': PriceRange(min: 15, max: 31, average: 23),
          'CH': PriceRange(min: 24, max: 49, average: 36),
          'CZ': PriceRange(min: 9, max: 18, average: 13),
          'PT': PriceRange(min: 9, max: 18, average: 13),
          'SE': PriceRange(min: 19, max: 39, average: 28),
          'DK': PriceRange(min: 21, max: 42, average: 30),
          'NO': PriceRange(min: 22, max: 45, average: 33),
          'FI': PriceRange(min: 18, max: 37, average: 27),
        },
      ),
      ServiceItem(
        id: 'electrical_cable_laying',
        categoryId: 'electrical',
        name: 'Cable Laying',
        nameRu: 'Прокладка кабеля',
        unit: 'meter',
        unitRu: 'пог.м',
        materialsCostRatio: 2.0,
        pricesByCountry: {
          'DE': PriceRange(min: 10, max: 20, average: 14),
          'FR': PriceRange(min: 9, max: 19, average: 13),
          'IT': PriceRange(min: 8, max: 17, average: 11),
          'ES': PriceRange(min: 7, max: 15, average: 10),
          'PL': PriceRange(min: 5, max: 11, average: 7),
          'NL': PriceRange(min: 11, max: 23, average: 16),
          'BE': PriceRange(min: 10, max: 21, average: 14),
          'AT': PriceRange(min: 10, max: 21, average: 14),
          'CH': PriceRange(min: 16, max: 33, average: 23),
          'CZ': PriceRange(min: 6, max: 12, average: 8),
          'PT': PriceRange(min: 6, max: 12, average: 8),
          'SE': PriceRange(min: 13, max: 26, average: 18),
          'DK': PriceRange(min: 14, max: 28, average: 19),
          'NO': PriceRange(min: 15, max: 30, average: 21),
          'FI': PriceRange(min: 12, max: 25, average: 17),
        },
      ),
    ];
  }

  List<ServiceItem> _getPlumbingServices() {
    return [
      ServiceItem(
        id: 'plumbing_sink',
        categoryId: 'plumbing',
        name: 'Sink Installation',
        nameRu: 'Установка раковины',
        unit: 'piece',
        unitRu: 'шт',
        materialsCostRatio: 2.2,
        pricesByCountry: {
          'DE': PriceRange(min: 120, max: 280, average: 200),
          'FR': PriceRange(min: 110, max: 260, average: 185),
          'IT': PriceRange(min: 100, max: 240, average: 170),
          'ES': PriceRange(min: 85, max: 200, average: 142),
          'PL': PriceRange(min: 60, max: 150, average: 105),
          'NL': PriceRange(min: 140, max: 320, average: 230),
          'BE': PriceRange(min: 130, max: 300, average: 215),
          'AT': PriceRange(min: 130, max: 300, average: 215),
          'CH': PriceRange(min: 200, max: 420, average: 310),
          'CZ': PriceRange(min: 70, max: 170, average: 120),
          'PT': PriceRange(min: 70, max: 170, average: 120),
          'SE': PriceRange(min: 150, max: 340, average: 245),
          'DK': PriceRange(min: 160, max: 360, average: 260),
          'NO': PriceRange(min: 170, max: 380, average: 275),
          'FI': PriceRange(min: 145, max: 330, average: 237),
        },
      ),
      ServiceItem(
        id: 'plumbing_toilet',
        categoryId: 'plumbing',
        name: 'Toilet Installation',
        nameRu: 'Установка унитаза',
        unit: 'piece',
        unitRu: 'шт',
        materialsCostRatio: 2.4,
        pricesByCountry: {
          'DE': PriceRange(min: 150, max: 350, average: 250),
          'FR': PriceRange(min: 140, max: 330, average: 235),
          'IT': PriceRange(min: 130, max: 310, average: 220),
          'ES': PriceRange(min: 110, max: 260, average: 185),
          'PL': PriceRange(min: 80, max: 190, average: 135),
          'NL': PriceRange(min: 170, max: 400, average: 285),
          'BE': PriceRange(min: 160, max: 380, average: 270),
          'AT': PriceRange(min: 160, max: 380, average: 270),
          'CH': PriceRange(min: 250, max: 530, average: 390),
          'CZ': PriceRange(min: 90, max: 220, average: 155),
          'PT': PriceRange(min: 90, max: 220, average: 155),
          'SE': PriceRange(min: 180, max: 420, average: 300),
          'DK': PriceRange(min: 190, max: 440, average: 315),
          'NO': PriceRange(min: 200, max: 460, average: 330),
          'FI': PriceRange(min: 175, max: 410, average: 292),
        },
      ),
      ServiceItem(
        id: 'plumbing_bathtub',
        categoryId: 'plumbing',
        name: 'Bathtub Installation',
        nameRu: 'Установка ванны',
        unit: 'piece',
        unitRu: 'шт',
        materialsCostRatio: 2.5,
        pricesByCountry: {
          'DE': PriceRange(min: 150, max: 300, average: 210),
          'FR': PriceRange(min: 142, max: 285, average: 199),
          'IT': PriceRange(min: 127, max: 255, average: 178),
          'ES': PriceRange(min: 112, max: 225, average: 157),
          'PL': PriceRange(min: 82, max: 165, average: 115),
          'NL': PriceRange(min: 172, max: 345, average: 241),
          'BE': PriceRange(min: 157, max: 315, average: 220),
          'AT': PriceRange(min: 157, max: 315, average: 220),
          'CH': PriceRange(min: 247, max: 495, average: 346),
          'CZ': PriceRange(min: 90, max: 180, average: 126),
          'PT': PriceRange(min: 90, max: 180, average: 126),
          'SE': PriceRange(min: 195, max: 390, average: 273),
          'DK': PriceRange(min: 210, max: 420, average: 294),
          'NO': PriceRange(min: 225, max: 450, average: 315),
          'FI': PriceRange(min: 187, max: 375, average: 262),
        },
      ),
      ServiceItem(
        id: 'plumbing_shower_cabin',
        categoryId: 'plumbing',
        name: 'Shower Cabin Installation',
        nameRu: 'Установка душевой кабины',
        unit: 'piece',
        unitRu: 'шт',
        materialsCostRatio: 2.3,
        pricesByCountry: {
          'DE': PriceRange(min: 180, max: 350, average: 250),
          'FR': PriceRange(min: 171, max: 332, average: 237),
          'IT': PriceRange(min: 153, max: 297, average: 212),
          'ES': PriceRange(min: 135, max: 262, average: 187),
          'PL': PriceRange(min: 99, max: 192, average: 137),
          'NL': PriceRange(min: 206, max: 402, average: 287),
          'BE': PriceRange(min: 189, max: 367, average: 262),
          'AT': PriceRange(min: 189, max: 367, average: 262),
          'CH': PriceRange(min: 297, max: 577, average: 412),
          'CZ': PriceRange(min: 108, max: 210, average: 150),
          'PT': PriceRange(min: 108, max: 210, average: 150),
          'SE': PriceRange(min: 234, max: 455, average: 325),
          'DK': PriceRange(min: 251, max: 489, average: 350),
          'NO': PriceRange(min: 270, max: 525, average: 375),
          'FI': PriceRange(min: 225, max: 437, average: 312),
        },
      ),
      ServiceItem(
        id: 'plumbing_kitchen_sink',
        categoryId: 'plumbing',
        name: 'Kitchen Sink Installation',
        nameRu: 'Установка кухонной мойки',
        unit: 'piece',
        unitRu: 'шт',
        materialsCostRatio: 2.2,
        pricesByCountry: {
          'DE': PriceRange(min: 80, max: 150, average: 110),
          'FR': PriceRange(min: 76, max: 142, average: 104),
          'IT': PriceRange(min: 68, max: 127, average: 93),
          'ES': PriceRange(min: 60, max: 112, average: 82),
          'PL': PriceRange(min: 44, max: 82, average: 60),
          'NL': PriceRange(min: 92, max: 172, average: 126),
          'BE': PriceRange(min: 84, max: 157, average: 115),
          'AT': PriceRange(min: 84, max: 157, average: 115),
          'CH': PriceRange(min: 132, max: 247, average: 181),
          'CZ': PriceRange(min: 48, max: 90, average: 66),
          'PT': PriceRange(min: 48, max: 90, average: 66),
          'SE': PriceRange(min: 104, max: 195, average: 143),
          'DK': PriceRange(min: 112, max: 210, average: 154),
          'NO': PriceRange(min: 120, max: 225, average: 165),
          'FI': PriceRange(min: 100, max: 187, average: 137),
        },
      ),
      ServiceItem(
        id: 'plumbing_mixer',
        categoryId: 'plumbing',
        name: 'Mixer Installation',
        nameRu: 'Установка смесителя',
        unit: 'piece',
        unitRu: 'шт',
        materialsCostRatio: 2.0,
        pricesByCountry: {
          'DE': PriceRange(min: 60, max: 120, average: 85),
          'FR': PriceRange(min: 57, max: 114, average: 80),
          'IT': PriceRange(min: 51, max: 102, average: 72),
          'ES': PriceRange(min: 45, max: 90, average: 63),
          'PL': PriceRange(min: 33, max: 66, average: 46),
          'NL': PriceRange(min: 69, max: 138, average: 97),
          'BE': PriceRange(min: 63, max: 126, average: 89),
          'AT': PriceRange(min: 63, max: 126, average: 89),
          'CH': PriceRange(min: 99, max: 198, average: 140),
          'CZ': PriceRange(min: 36, max: 72, average: 51),
          'PT': PriceRange(min: 36, max: 72, average: 51),
          'SE': PriceRange(min: 78, max: 156, average: 110),
          'DK': PriceRange(min: 84, max: 168, average: 118),
          'NO': PriceRange(min: 90, max: 180, average: 127),
          'FI': PriceRange(min: 75, max: 150, average: 106),
        },
      ),
      ServiceItem(
        id: 'plumbing_pipe_replacement',
        categoryId: 'plumbing',
        name: 'Pipe Replacement',
        nameRu: 'Замена труб',
        unit: 'meter',
        unitRu: 'пог.м',
        materialsCostRatio: 2.3,
        pricesByCountry: {
          'DE': PriceRange(min: 35, max: 65, average: 48),
          'FR': PriceRange(min: 33, max: 61, average: 45),
          'IT': PriceRange(min: 29, max: 55, average: 40),
          'ES': PriceRange(min: 26, max: 48, average: 36),
          'PL': PriceRange(min: 19, max: 35, average: 26),
          'NL': PriceRange(min: 40, max: 74, average: 55),
          'BE': PriceRange(min: 36, max: 68, average: 50),
          'AT': PriceRange(min: 36, max: 68, average: 50),
          'CH': PriceRange(min: 57, max: 107, average: 79),
          'CZ': PriceRange(min: 21, max: 39, average: 28),
          'PT': PriceRange(min: 21, max: 39, average: 28),
          'SE': PriceRange(min: 45, max: 84, average: 62),
          'DK': PriceRange(min: 49, max: 91, average: 67),
          'NO': PriceRange(min: 52, max: 97, average: 72),
          'FI': PriceRange(min: 43, max: 81, average: 60),
        },
      ),
    ];
  }

  List<ServiceItem> _getFlooringServices() {
    return [
      ServiceItem(
        id: 'flooring_laminate',
        categoryId: 'flooring',
        name: 'Laminate Flooring Installation',
        nameRu: 'Укладка ламината',
        unit: 'sqm',
        unitRu: 'м²',
        materialsCostRatio: 2.5,
        pricesByCountry: {
          'DE': PriceRange(min: 25, max: 50, average: 37),
          'FR': PriceRange(min: 23, max: 47, average: 35),
          'IT': PriceRange(min: 20, max: 42, average: 31),
          'ES': PriceRange(min: 18, max: 38, average: 28),
          'PL': PriceRange(min: 12, max: 28, average: 20),
          'NL': PriceRange(min: 30, max: 58, average: 44),
          'BE': PriceRange(min: 27, max: 54, average: 40),
          'AT': PriceRange(min: 27, max: 54, average: 40),
          'CH': PriceRange(min: 42, max: 78, average: 60),
          'CZ': PriceRange(min: 15, max: 32, average: 23),
          'PT': PriceRange(min: 15, max: 32, average: 23),
          'SE': PriceRange(min: 33, max: 62, average: 47),
          'DK': PriceRange(min: 35, max: 65, average: 50),
          'NO': PriceRange(min: 37, max: 68, average: 52),
          'FI': PriceRange(min: 32, max: 60, average: 46),
        },
      ),
      ServiceItem(
        id: 'flooring_parquet',
        categoryId: 'flooring',
        name: 'Parquet Flooring Installation',
        nameRu: 'Укладка паркета',
        unit: 'sqm',
        unitRu: 'м²',
        materialsCostRatio: 3.0,
        pricesByCountry: {
          'DE': PriceRange(min: 40, max: 80, average: 60),
          'FR': PriceRange(min: 38, max: 76, average: 57),
          'IT': PriceRange(min: 35, max: 70, average: 52),
          'ES': PriceRange(min: 30, max: 62, average: 46),
          'PL': PriceRange(min: 22, max: 48, average: 35),
          'NL': PriceRange(min: 48, max: 92, average: 70),
          'BE': PriceRange(min: 44, max: 86, average: 65),
          'AT': PriceRange(min: 44, max: 86, average: 65),
          'CH': PriceRange(min: 65, max: 125, average: 95),
          'CZ': PriceRange(min: 26, max: 55, average: 40),
          'PT': PriceRange(min: 26, max: 55, average: 40),
          'SE': PriceRange(min: 52, max: 98, average: 75),
          'DK': PriceRange(min: 55, max: 103, average: 79),
          'NO': PriceRange(min: 58, max: 108, average: 83),
          'FI': PriceRange(min: 50, max: 96, average: 73),
        },
      ),
    ];
  }

  List<ServiceItem> _getTilingServices() {
    return [
      ServiceItem(
        id: 'tiling_floor',
        categoryId: 'tiling',
        name: 'Floor Tiling',
        nameRu: 'Облицовка пола плиткой',
        unit: 'sqm',
        unitRu: 'м²',
        materialsCostRatio: 2.2,
        pricesByCountry: {
          'DE': PriceRange(min: 35, max: 70, average: 52),
          'FR': PriceRange(min: 33, max: 66, average: 49),
          'IT': PriceRange(min: 30, max: 60, average: 45),
          'ES': PriceRange(min: 25, max: 52, average: 38),
          'PL': PriceRange(min: 18, max: 40, average: 29),
          'NL': PriceRange(min: 42, max: 82, average: 62),
          'BE': PriceRange(min: 38, max: 76, average: 57),
          'AT': PriceRange(min: 38, max: 76, average: 57),
          'CH': PriceRange(min: 58, max: 110, average: 84),
          'CZ': PriceRange(min: 22, max: 46, average: 34),
          'PT': PriceRange(min: 22, max: 46, average: 34),
          'SE': PriceRange(min: 45, max: 88, average: 66),
          'DK': PriceRange(min: 48, max: 92, average: 70),
          'NO': PriceRange(min: 50, max: 96, average: 73),
          'FI': PriceRange(min: 43, max: 85, average: 64),
        },
      ),
      ServiceItem(
        id: 'tiling_wall',
        categoryId: 'tiling',
        name: 'Wall Tiling',
        nameRu: 'Облицовка стен плиткой',
        unit: 'sqm',
        unitRu: 'м²',
        materialsCostRatio: 2.0,
        pricesByCountry: {
          'DE': PriceRange(min: 40, max: 80, average: 60),
          'FR': PriceRange(min: 38, max: 76, average: 57),
          'IT': PriceRange(min: 35, max: 70, average: 52),
          'ES': PriceRange(min: 30, max: 62, average: 46),
          'PL': PriceRange(min: 22, max: 48, average: 35),
          'NL': PriceRange(min: 48, max: 92, average: 70),
          'BE': PriceRange(min: 44, max: 86, average: 65),
          'AT': PriceRange(min: 44, max: 86, average: 65),
          'CH': PriceRange(min: 65, max: 125, average: 95),
          'CZ': PriceRange(min: 26, max: 55, average: 40),
          'PT': PriceRange(min: 26, max: 55, average: 40),
          'SE': PriceRange(min: 52, max: 98, average: 75),
          'DK': PriceRange(min: 55, max: 103, average: 79),
          'NO': PriceRange(min: 58, max: 108, average: 83),
          'FI': PriceRange(min: 50, max: 96, average: 73),
        },
      ),
      ServiceItem(
        id: 'tiling_kitchen_backsplash',
        categoryId: 'tiling',
        name: 'Kitchen Backsplash',
        nameRu: 'Кухонный фартук',
        unit: 'sqm',
        unitRu: 'м²',
        materialsCostRatio: 2.2,
        pricesByCountry: {
          'DE': PriceRange(min: 40, max: 75, average: 55),
          'FR': PriceRange(min: 38, max: 71, average: 52),
          'IT': PriceRange(min: 34, max: 63, average: 46),
          'ES': PriceRange(min: 30, max: 56, average: 41),
          'PL': PriceRange(min: 22, max: 41, average: 30),
          'NL': PriceRange(min: 46, max: 86, average: 63),
          'BE': PriceRange(min: 42, max: 78, average: 57),
          'AT': PriceRange(min: 42, max: 78, average: 57),
          'CH': PriceRange(min: 66, max: 123, average: 90),
          'CZ': PriceRange(min: 24, max: 45, average: 33),
          'PT': PriceRange(min: 24, max: 45, average: 33),
          'SE': PriceRange(min: 52, max: 97, average: 71),
          'DK': PriceRange(min: 56, max: 105, average: 77),
          'NO': PriceRange(min: 60, max: 112, average: 82),
          'FI': PriceRange(min: 50, max: 93, average: 68),
        },
      ),
      ServiceItem(
        id: 'tiling_bathroom',
        categoryId: 'tiling',
        name: 'Bathroom Tiling',
        nameRu: 'Облицовка ванной',
        unit: 'sqm',
        unitRu: 'м²',
        materialsCostRatio: 2.0,
        pricesByCountry: {
          'DE': PriceRange(min: 35, max: 65, average: 48),
          'FR': PriceRange(min: 33, max: 61, average: 45),
          'IT': PriceRange(min: 29, max: 55, average: 40),
          'ES': PriceRange(min: 26, max: 48, average: 36),
          'PL': PriceRange(min: 19, max: 35, average: 26),
          'NL': PriceRange(min: 40, max: 74, average: 55),
          'BE': PriceRange(min: 36, max: 68, average: 50),
          'AT': PriceRange(min: 36, max: 68, average: 50),
          'CH': PriceRange(min: 57, max: 107, average: 79),
          'CZ': PriceRange(min: 21, max: 39, average: 28),
          'PT': PriceRange(min: 21, max: 39, average: 28),
          'SE': PriceRange(min: 45, max: 84, average: 62),
          'DK': PriceRange(min: 49, max: 91, average: 67),
          'NO': PriceRange(min: 52, max: 97, average: 72),
          'FI': PriceRange(min: 43, max: 81, average: 60),
        },
      ),
      ServiceItem(
        id: 'tiling_grout',
        categoryId: 'tiling',
        name: 'Grout Application',
        nameRu: 'Затирка швов',
        unit: 'sqm',
        unitRu: 'м²',
        materialsCostRatio: 1.5,
        pricesByCountry: {
          'DE': PriceRange(min: 8, max: 15, average: 11),
          'FR': PriceRange(min: 7, max: 14, average: 10),
          'IT': PriceRange(min: 6, max: 12, average: 9),
          'ES': PriceRange(min: 6, max: 11, average: 8),
          'PL': PriceRange(min: 4, max: 8, average: 6),
          'NL': PriceRange(min: 9, max: 17, average: 12),
          'BE': PriceRange(min: 8, max: 15, average: 11),
          'AT': PriceRange(min: 8, max: 15, average: 11),
          'CH': PriceRange(min: 13, max: 24, average: 18),
          'CZ': PriceRange(min: 4, max: 9, average: 6),
          'PT': PriceRange(min: 4, max: 9, average: 6),
          'SE': PriceRange(min: 10, max: 19, average: 14),
          'DK': PriceRange(min: 11, max: 21, average: 15),
          'NO': PriceRange(min: 12, max: 22, average: 16),
          'FI': PriceRange(min: 10, max: 18, average: 13),
        },
      ),
    ];
  }

  List<ServiceItem> _getCarpentryServices() {
    return [
      ServiceItem(
        id: 'carpentry_door',
        categoryId: 'carpentry',
        name: 'Door Installation',
        nameRu: 'Установка двери',
        unit: 'piece',
        unitRu: 'шт',
        pricesByCountry: {
          'DE': PriceRange(min: 180, max: 400, average: 290),
          'FR': PriceRange(min: 170, max: 380, average: 275),
          'IT': PriceRange(min: 160, max: 360, average: 260),
          'ES': PriceRange(min: 140, max: 320, average: 230),
          'PL': PriceRange(min: 100, max: 240, average: 170),
          'NL': PriceRange(min: 210, max: 460, average: 335),
          'BE': PriceRange(min: 195, max: 435, average: 315),
          'AT': PriceRange(min: 195, max: 435, average: 315),
          'CH': PriceRange(min: 300, max: 620, average: 460),
          'CZ': PriceRange(min: 115, max: 275, average: 195),
          'PT': PriceRange(min: 115, max: 275, average: 195),
          'SE': PriceRange(min: 225, max: 490, average: 357),
          'DK': PriceRange(min: 240, max: 515, average: 377),
          'NO': PriceRange(min: 250, max: 540, average: 395),
          'FI': PriceRange(min: 220, max: 480, average: 350),
        },
      ),
      ServiceItem(
        id: 'carpentry_window',
        categoryId: 'carpentry',
        name: 'Window Installation',
        nameRu: 'Установка окна',
        unit: 'piece',
        unitRu: 'шт',
        pricesByCountry: {
          'DE': PriceRange(min: 250, max: 550, average: 400),
          'FR': PriceRange(min: 240, max: 530, average: 385),
          'IT': PriceRange(min: 220, max: 500, average: 360),
          'ES': PriceRange(min: 190, max: 440, average: 315),
          'PL': PriceRange(min: 140, max: 330, average: 235),
          'NL': PriceRange(min: 290, max: 630, average: 460),
          'BE': PriceRange(min: 270, max: 600, average: 435),
          'AT': PriceRange(min: 270, max: 600, average: 435),
          'CH': PriceRange(min: 420, max: 850, average: 635),
          'CZ': PriceRange(min: 160, max: 380, average: 270),
          'PT': PriceRange(min: 160, max: 380, average: 270),
          'SE': PriceRange(min: 310, max: 670, average: 490),
          'DK': PriceRange(min: 330, max: 710, average: 520),
          'NO': PriceRange(min: 350, max: 740, average: 545),
          'FI': PriceRange(min: 305, max: 660, average: 482),
        },
      ),
    ];
  }

  List<ServiceItem> _getRoofingServices() {
    return [
      ServiceItem(
        id: 'roofing_tile_replacement',
        categoryId: 'roofing',
        name: 'Roof Tile Replacement',
        nameRu: 'Замена черепицы',
        unit: 'sqm',
        unitRu: 'м²',
        materialsCostRatio: 2.8,
        pricesByCountry: {
          'DE': PriceRange(min: 80, max: 150, average: 115),
          'FR': PriceRange(min: 75, max: 140, average: 107),
          'IT': PriceRange(min: 70, max: 130, average: 100),
          'ES': PriceRange(min: 60, max: 115, average: 87),
          'PL': PriceRange(min: 45, max: 85, average: 65),
          'NL': PriceRange(min: 95, max: 175, average: 135),
          'BE': PriceRange(min: 87, max: 162, average: 124),
          'AT': PriceRange(min: 87, max: 162, average: 124),
          'CH': PriceRange(min: 135, max: 240, average: 187),
          'CZ': PriceRange(min: 52, max: 98, average: 75),
          'PT': PriceRange(min: 52, max: 98, average: 75),
          'SE': PriceRange(min: 102, max: 187, average: 144),
          'DK': PriceRange(min: 108, max: 198, average: 153),
          'NO': PriceRange(min: 115, max: 210, average: 162),
          'FI': PriceRange(min: 100, max: 185, average: 142),
        },
      ),
      ServiceItem(
        id: 'roofing_waterproofing',
        categoryId: 'roofing',
        name: 'Roof Waterproofing',
        nameRu: 'Гидроизоляция кровли',
        unit: 'sqm',
        unitRu: 'м²',
        materialsCostRatio: 2.5,
        pricesByCountry: {
          'DE': PriceRange(min: 30, max: 60, average: 45),
          'FR': PriceRange(min: 28, max: 56, average: 42),
          'IT': PriceRange(min: 25, max: 52, average: 38),
          'ES': PriceRange(min: 22, max: 45, average: 33),
          'PL': PriceRange(min: 16, max: 33, average: 24),
          'NL': PriceRange(min: 35, max: 70, average: 52),
          'BE': PriceRange(min: 32, max: 65, average: 48),
          'AT': PriceRange(min: 32, max: 65, average: 48),
          'CH': PriceRange(min: 50, max: 95, average: 72),
          'CZ': PriceRange(min: 18, max: 38, average: 28),
          'PT': PriceRange(min: 18, max: 38, average: 28),
          'SE': PriceRange(min: 38, max: 75, average: 56),
          'DK': PriceRange(min: 40, max: 80, average: 60),
          'NO': PriceRange(min: 43, max: 85, average: 64),
          'FI': PriceRange(min: 37, max: 73, average: 55),
        },
      ),
      ServiceItem(
        id: 'roofing_gutter_installation',
        categoryId: 'roofing',
        name: 'Rain Gutter Installation',
        nameRu: 'Установка водостока',
        unit: 'meter',
        unitRu: 'м',
        materialsCostRatio: 2.6,
        pricesByCountry: {
          'DE': PriceRange(min: 40, max: 80, average: 60),
          'FR': PriceRange(min: 38, max: 75, average: 56),
          'IT': PriceRange(min: 35, max: 70, average: 52),
          'ES': PriceRange(min: 30, max: 60, average: 45),
          'PL': PriceRange(min: 22, max: 45, average: 33),
          'NL': PriceRange(min: 47, max: 92, average: 69),
          'BE': PriceRange(min: 43, max: 87, average: 65),
          'AT': PriceRange(min: 43, max: 87, average: 65),
          'CH': PriceRange(min: 67, max: 125, average: 96),
          'CZ': PriceRange(min: 25, max: 52, average: 38),
          'PT': PriceRange(min: 25, max: 52, average: 38),
          'SE': PriceRange(min: 51, max: 98, average: 74),
          'DK': PriceRange(min: 54, max: 104, average: 79),
          'NO': PriceRange(min: 57, max: 110, average: 83),
          'FI': PriceRange(min: 50, max: 96, average: 73),
        },
      ),
    ];
  }

  List<ServiceItem> _getFacadeServices() {
    return [
      ServiceItem(
        id: 'facade_insulation',
        categoryId: 'facade',
        name: 'Facade Insulation',
        nameRu: 'Утепление фасада',
        unit: 'sqm',
        unitRu: 'м²',
        materialsCostRatio: 2.3,
        pricesByCountry: {
          'DE': PriceRange(min: 90, max: 180, average: 135),
          'FR': PriceRange(min: 85, max: 170, average: 127),
          'IT': PriceRange(min: 80, max: 160, average: 120),
          'ES': PriceRange(min: 70, max: 140, average: 105),
          'PL': PriceRange(min: 50, max: 100, average: 75),
          'NL': PriceRange(min: 105, max: 210, average: 157),
          'BE': PriceRange(min: 98, max: 195, average: 146),
          'AT': PriceRange(min: 98, max: 195, average: 146),
          'CH': PriceRange(min: 150, max: 280, average: 215),
          'CZ': PriceRange(min: 58, max: 115, average: 86),
          'PT': PriceRange(min: 58, max: 115, average: 86),
          'SE': PriceRange(min: 112, max: 224, average: 168),
          'DK': PriceRange(min: 119, max: 238, average: 178),
          'NO': PriceRange(min: 126, max: 252, average: 189),
          'FI': PriceRange(min: 110, max: 220, average: 165),
        },
      ),
      ServiceItem(
        id: 'facade_plastering',
        categoryId: 'facade',
        name: 'Facade Plastering',
        nameRu: 'Оштукатуривание фасада',
        unit: 'sqm',
        unitRu: 'м²',
        materialsCostRatio: 2.0,
        pricesByCountry: {
          'DE': PriceRange(min: 50, max: 100, average: 75),
          'FR': PriceRange(min: 47, max: 94, average: 70),
          'IT': PriceRange(min: 44, max: 88, average: 66),
          'ES': PriceRange(min: 38, max: 76, average: 57),
          'PL': PriceRange(min: 28, max: 56, average: 42),
          'NL': PriceRange(min: 58, max: 116, average: 87),
          'BE': PriceRange(min: 54, max: 108, average: 81),
          'AT': PriceRange(min: 54, max: 108, average: 81),
          'CH': PriceRange(min: 84, max: 155, average: 119),
          'CZ': PriceRange(min: 32, max: 64, average: 48),
          'PT': PriceRange(min: 32, max: 64, average: 48),
          'SE': PriceRange(min: 62, max: 124, average: 93),
          'DK': PriceRange(min: 66, max: 131, average: 98),
          'NO': PriceRange(min: 70, max: 139, average: 104),
          'FI': PriceRange(min: 61, max: 121, average: 91),
        },
      ),
    ];
  }

  List<ServiceItem> _getHVACServices() {
    return [
      ServiceItem(
        id: 'hvac_radiator',
        categoryId: 'hvac',
        name: 'Radiator Installation',
        nameRu: 'Установка радиатора',
        unit: 'piece',
        unitRu: 'шт',
        materialsCostRatio: 3.5,
        pricesByCountry: {
          'DE': PriceRange(min: 200, max: 450, average: 325),
          'FR': PriceRange(min: 190, max: 425, average: 307),
          'IT': PriceRange(min: 180, max: 400, average: 290),
          'ES': PriceRange(min: 155, max: 350, average: 252),
          'PL': PriceRange(min: 115, max: 260, average: 187),
          'NL': PriceRange(min: 235, max: 520, average: 377),
          'BE': PriceRange(min: 220, max: 490, average: 355),
          'AT': PriceRange(min: 220, max: 490, average: 355),
          'CH': PriceRange(min: 340, max: 700, average: 520),
          'CZ': PriceRange(min: 132, max: 300, average: 216),
          'PT': PriceRange(min: 132, max: 300, average: 216),
          'SE': PriceRange(min: 251, max: 555, average: 403),
          'DK': PriceRange(min: 266, max: 588, average: 427),
          'NO': PriceRange(min: 282, max: 625, average: 453),
          'FI': PriceRange(min: 246, max: 546, average: 396),
        },
      ),
      ServiceItem(
        id: 'hvac_ac_installation',
        categoryId: 'hvac',
        name: 'Air Conditioning Installation',
        nameRu: 'Установка кондиционера',
        unit: 'piece',
        unitRu: 'шт',
        materialsCostRatio: 4.0,
        pricesByCountry: {
          'DE': PriceRange(min: 500, max: 1200, average: 850),
          'FR': PriceRange(min: 480, max: 1150, average: 815),
          'IT': PriceRange(min: 450, max: 1100, average: 775),
          'ES': PriceRange(min: 400, max: 950, average: 675),
          'PL': PriceRange(min: 300, max: 700, average: 500),
          'NL': PriceRange(min: 580, max: 1380, average: 980),
          'BE': PriceRange(min: 545, max: 1300, average: 922),
          'AT': PriceRange(min: 545, max: 1300, average: 922),
          'CH': PriceRange(min: 850, max: 1900, average: 1375),
          'CZ': PriceRange(min: 345, max: 810, average: 577),
          'PT': PriceRange(min: 345, max: 810, average: 577),
          'SE': PriceRange(min: 620, max: 1470, average: 1045),
          'DK': PriceRange(min: 658, max: 1560, average: 1109),
          'NO': PriceRange(min: 697, max: 1650, average: 1173),
          'FI': PriceRange(min: 609, max: 1443, average: 1026),
        },
      ),
      ServiceItem(
        id: 'hvac_ventilation',
        categoryId: 'hvac',
        name: 'Ventilation System Installation',
        nameRu: 'Установка вентиляции',
        unit: 'sqm',
        unitRu: 'м²',
        materialsCostRatio: 3.2,
        pricesByCountry: {
          'DE': PriceRange(min: 40, max: 90, average: 65),
          'FR': PriceRange(min: 38, max: 85, average: 61),
          'IT': PriceRange(min: 35, max: 80, average: 57),
          'ES': PriceRange(min: 30, max: 70, average: 50),
          'PL': PriceRange(min: 22, max: 52, average: 37),
          'NL': PriceRange(min: 47, max: 104, average: 75),
          'BE': PriceRange(min: 44, max: 98, average: 71),
          'AT': PriceRange(min: 44, max: 98, average: 71),
          'CH': PriceRange(min: 68, max: 143, average: 105),
          'CZ': PriceRange(min: 26, max: 60, average: 43),
          'PT': PriceRange(min: 26, max: 60, average: 43),
          'SE': PriceRange(min: 50, max: 111, average: 80),
          'DK': PriceRange(min: 53, max: 118, average: 85),
          'NO': PriceRange(min: 56, max: 125, average: 90),
          'FI': PriceRange(min: 49, max: 109, average: 79),
        },
      ),
    ];
  }

  List<ServiceItem> _getGlazingServices() {
    return [
      ServiceItem(
        id: 'glazing_window_pvc',
        categoryId: 'glazing',
        name: 'PVC Window Installation',
        nameRu: 'Установка пластикового окна',
        unit: 'piece',
        unitRu: 'шт',
        materialsCostRatio: 4.5,
        pricesByCountry: {
          'DE': PriceRange(min: 300, max: 700, average: 500),
          'FR': PriceRange(min: 285, max: 665, average: 475),
          'IT': PriceRange(min: 270, max: 630, average: 450),
          'ES': PriceRange(min: 235, max: 550, average: 392),
          'PL': PriceRange(min: 175, max: 410, average: 292),
          'NL': PriceRange(min: 350, max: 810, average: 580),
          'BE': PriceRange(min: 330, max: 765, average: 547),
          'AT': PriceRange(min: 330, max: 765, average: 547),
          'CH': PriceRange(min: 510, max: 1085, average: 797),
          'CZ': PriceRange(min: 202, max: 473, average: 337),
          'PT': PriceRange(min: 202, max: 473, average: 337),
          'SE': PriceRange(min: 375, max: 865, average: 620),
          'DK': PriceRange(min: 397, max: 917, average: 657),
          'NO': PriceRange(min: 421, max: 973, average: 697),
          'FI': PriceRange(min: 368, max: 850, average: 609),
        },
      ),
      ServiceItem(
        id: 'glazing_door_installation',
        categoryId: 'glazing',
        name: 'Interior Door Installation',
        nameRu: 'Установка межкомнатной двери',
        unit: 'piece',
        unitRu: 'шт',
        materialsCostRatio: 3.8,
        pricesByCountry: {
          'DE': PriceRange(min: 150, max: 350, average: 250),
          'FR': PriceRange(min: 142, max: 332, average: 237),
          'IT': PriceRange(min: 135, max: 315, average: 225),
          'ES': PriceRange(min: 117, max: 275, average: 196),
          'PL': PriceRange(min: 87, max: 205, average: 146),
          'NL': PriceRange(min: 175, max: 405, average: 290),
          'BE': PriceRange(min: 165, max: 382, average: 273),
          'AT': PriceRange(min: 165, max: 382, average: 273),
          'CH': PriceRange(min: 255, max: 542, average: 398),
          'CZ': PriceRange(min: 101, max: 236, average: 168),
          'PT': PriceRange(min: 101, max: 236, average: 168),
          'SE': PriceRange(min: 187, max: 432, average: 310),
          'DK': PriceRange(min: 198, max: 458, average: 328),
          'NO': PriceRange(min: 210, max: 486, average: 348),
          'FI': PriceRange(min: 184, max: 425, average: 304),
        },
      ),
    ];
  }

  List<ServiceItem> _getPlasteringServices() {
    return [
      ServiceItem(
        id: 'plastering_wall',
        categoryId: 'plastering',
        name: 'Wall Plastering',
        nameRu: 'Штукатурка стен',
        unit: 'sqm',
        unitRu: 'м²',
        materialsCostRatio: 1.5,
        pricesByCountry: {
          'DE': PriceRange(min: 25, max: 50, average: 37),
          'FR': PriceRange(min: 23, max: 47, average: 35),
          'IT': PriceRange(min: 22, max: 44, average: 33),
          'ES': PriceRange(min: 19, max: 38, average: 28),
          'PL': PriceRange(min: 14, max: 28, average: 21),
          'NL': PriceRange(min: 29, max: 58, average: 43),
          'BE': PriceRange(min: 27, max: 54, average: 40),
          'AT': PriceRange(min: 27, max: 54, average: 40),
          'CH': PriceRange(min: 42, max: 77, average: 59),
          'CZ': PriceRange(min: 16, max: 32, average: 24),
          'PT': PriceRange(min: 16, max: 32, average: 24),
          'SE': PriceRange(min: 31, max: 62, average: 46),
          'DK': PriceRange(min: 33, max: 66, average: 49),
          'NO': PriceRange(min: 35, max: 70, average: 52),
          'FI': PriceRange(min: 30, max: 61, average: 45),
        },
      ),
      ServiceItem(
        id: 'plastering_drywall',
        categoryId: 'plastering',
        name: 'Drywall Installation',
        nameRu: 'Монтаж гипсокартона',
        unit: 'sqm',
        unitRu: 'м²',
        materialsCostRatio: 1.4,
        pricesByCountry: {
          'DE': PriceRange(min: 20, max: 40, average: 30),
          'FR': PriceRange(min: 19, max: 38, average: 28),
          'IT': PriceRange(min: 17, max: 35, average: 26),
          'ES': PriceRange(min: 15, max: 30, average: 22),
          'PL': PriceRange(min: 11, max: 22, average: 16),
          'NL': PriceRange(min: 23, max: 46, average: 34),
          'BE': PriceRange(min: 22, max: 43, average: 32),
          'AT': PriceRange(min: 22, max: 43, average: 32),
          'CH': PriceRange(min: 33, max: 62, average: 47),
          'CZ': PriceRange(min: 13, max: 26, average: 19),
          'PT': PriceRange(min: 13, max: 26, average: 19),
          'SE': PriceRange(min: 25, max: 50, average: 37),
          'DK': PriceRange(min: 26, max: 52, average: 39),
          'NO': PriceRange(min: 28, max: 56, average: 42),
          'FI': PriceRange(min: 24, max: 49, average: 36),
        },
      ),
      ServiceItem(
        id: 'plastering_ceiling',
        categoryId: 'plastering',
        name: 'Ceiling Plastering',
        nameRu: 'Штукатурка потолка',
        unit: 'sqm',
        unitRu: 'м²',
        materialsCostRatio: 1.6,
        pricesByCountry: {
          'DE': PriceRange(min: 30, max: 60, average: 45),
          'FR': PriceRange(min: 28, max: 57, average: 42),
          'IT': PriceRange(min: 26, max: 53, average: 39),
          'ES': PriceRange(min: 23, max: 46, average: 34),
          'PL': PriceRange(min: 17, max: 34, average: 25),
          'NL': PriceRange(min: 35, max: 69, average: 52),
          'BE': PriceRange(min: 33, max: 65, average: 49),
          'AT': PriceRange(min: 33, max: 65, average: 49),
          'CH': PriceRange(min: 51, max: 93, average: 72),
          'CZ': PriceRange(min: 19, max: 39, average: 29),
          'PT': PriceRange(min: 19, max: 39, average: 29),
          'SE': PriceRange(min: 37, max: 74, average: 55),
          'DK': PriceRange(min: 39, max: 78, average: 58),
          'NO': PriceRange(min: 42, max: 83, average: 62),
          'FI': PriceRange(min: 36, max: 73, average: 54),
        },
      ),
    ];
  }

  List<ServiceItem> _getLandscapingServices() {
    return [
      ServiceItem(
        id: 'landscaping_lawn',
        categoryId: 'landscaping',
        name: 'Lawn Installation',
        nameRu: 'Устройство газона',
        unit: 'sqm',
        unitRu: 'м²',
        materialsCostRatio: 1.9,
        pricesByCountry: {
          'DE': PriceRange(min: 15, max: 35, average: 25),
          'FR': PriceRange(min: 14, max: 33, average: 23),
          'IT': PriceRange(min: 13, max: 31, average: 22),
          'ES': PriceRange(min: 11, max: 27, average: 19),
          'PL': PriceRange(min: 8, max: 20, average: 14),
          'NL': PriceRange(min: 17, max: 40, average: 28),
          'BE': PriceRange(min: 16, max: 38, average: 27),
          'AT': PriceRange(min: 16, max: 38, average: 27),
          'CH': PriceRange(min: 25, max: 54, average: 39),
          'CZ': PriceRange(min: 9, max: 23, average: 16),
          'PT': PriceRange(min: 9, max: 23, average: 16),
          'SE': PriceRange(min: 19, max: 43, average: 31),
          'DK': PriceRange(min: 20, max: 45, average: 32),
          'NO': PriceRange(min: 21, max: 48, average: 34),
          'FI': PriceRange(min: 18, max: 42, average: 30),
        },
      ),
      ServiceItem(
        id: 'landscaping_paving',
        categoryId: 'landscaping',
        name: 'Garden Paving',
        nameRu: 'Укладка тротуарной плитки',
        unit: 'sqm',
        unitRu: 'м²',
        materialsCostRatio: 2.1,
        pricesByCountry: {
          'DE': PriceRange(min: 40, max: 90, average: 65),
          'FR': PriceRange(min: 38, max: 85, average: 61),
          'IT': PriceRange(min: 35, max: 80, average: 57),
          'ES': PriceRange(min: 30, max: 70, average: 50),
          'PL': PriceRange(min: 22, max: 52, average: 37),
          'NL': PriceRange(min: 47, max: 104, average: 75),
          'BE': PriceRange(min: 44, max: 98, average: 71),
          'AT': PriceRange(min: 44, max: 98, average: 71),
          'CH': PriceRange(min: 68, max: 143, average: 105),
          'CZ': PriceRange(min: 26, max: 60, average: 43),
          'PT': PriceRange(min: 26, max: 60, average: 43),
          'SE': PriceRange(min: 50, max: 111, average: 80),
          'DK': PriceRange(min: 53, max: 118, average: 85),
          'NO': PriceRange(min: 56, max: 125, average: 90),
          'FI': PriceRange(min: 49, max: 109, average: 79),
        },
      ),
      ServiceItem(
        id: 'landscaping_fence',
        categoryId: 'landscaping',
        name: 'Fence Installation',
        nameRu: 'Установка забора',
        unit: 'meter',
        unitRu: 'м',
        materialsCostRatio: 2.2,
        pricesByCountry: {
          'DE': PriceRange(min: 80, max: 180, average: 130),
          'FR': PriceRange(min: 76, max: 171, average: 123),
          'IT': PriceRange(min: 72, max: 162, average: 117),
          'ES': PriceRange(min: 62, max: 140, average: 101),
          'PL': PriceRange(min: 46, max: 104, average: 75),
          'NL': PriceRange(min: 93, max: 207, average: 150),
          'BE': PriceRange(min: 88, max: 196, average: 142),
          'AT': PriceRange(min: 88, max: 196, average: 142),
          'CH': PriceRange(min: 136, max: 286, average: 211),
          'CZ': PriceRange(min: 53, max: 120, average: 86),
          'PT': PriceRange(min: 53, max: 120, average: 86),
          'SE': PriceRange(min: 100, max: 221, average: 160),
          'DK': PriceRange(min: 106, max: 234, average: 170),
          'NO': PriceRange(min: 112, max: 248, average: 180),
          'FI': PriceRange(min: 98, max: 217, average: 157),
        },
      ),
    ];
  }
}
